doc/manual/statements.tex
sources/sort.c

Never print statistics for small buffer sort, if ShortStatsMax is 0
Often I want statistics enabled, but only for the final sort (to see the number of terms in output).
For large calculations, one can get many thousands of lines for small-buffer sorts, even with fewerstats set as large as possible.

Change behaviour of "On fewerstatistics 0"

---

check/features.frm
doc/manual/setup.tex
sources/sch.c
sources/setfile.c

Allow disabling the continuation line limit by setting `ContinuationLines` to 0.
Also fix the documentation: the continuation line limit applies not only for Fortran, but for all formats.
This fixes issue #392.

Allow setting ContinuationLines to 0, meaning infinity (fixes #392)

---

sources/findpat.c
sources/float.c
sources/grcc.cc
sources/grcc.h
sources/minos.h
sources/pattern.c
sources/poly.cc
sources/startup.c
sources/tables.c
sources/threads.c
sources/tools.c

found using
`codespell -L=nd,te,nin,ba,sav,pres,numer,dum,childs sources/`

just fixing a few typos in sources/

---

INSTALL
check/README.md
check/check.rb
configure.ac

This patch makes `check.rb` properly kill test processes that have timed out.
@jodavies Could you give it a try?

check.rb: terminating timed-out processes properly

---

check/fixes.frm
sources/sch.c

Mathematica does not interpret "a.b^2" as intended, add brackets around dot products when printing with `Format mathematica;` regardless of the presence of a power.
Fixes #460

Add brackets around dot products for format mathematica

---

check/fixes.frm
sources/module.c

Move pointer beyond the function name after enabling the poly(rat)fun
Fixes #313

Fix comma syntax for moduleoption poly(rat)run,name

---

sources/optimize.cc

Don't double-increment t when computing sumsize.
Should fix Issue #447.

Fix Issue #447

---

check/check.rb
check/features.frm

Here, I simply set constant memory requirements. (Maybe this is enough?) In principle, one can consider the number of cpus etc. but it may be too complicated.
The serial version requires 8 GB (in SI, not GiB), so 8 GiB system memory is enough to run it. The threaded/mpi versions need 20GB. Note that [16 GiB is available on GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).

Don't run moebius_3 test when available memory is limited

---

check/fixes.frm
sources/sch.c

Avoid accessing array out of bounds when a set is empty.
Closes #486

Fix printing empty set with on codes

---

check/fixes.frm
sources/spectator.c

Check that spectator names are not null pointers, before comparing.
RemoveSpectator leaves a hole in the SpectatorFiles array. One could fix this by moving all higher spectators to fill the hole, but creating new spectators later will at least fill the holes, currently.
Closes #231

Fix RemoveSpectator after making holes in array

---

check/fixes.frm
sources/sch.c

If there are blank lines in the output (for eg when printing a bracketed expression) mathematica considers the expression to have finished. This is avoided by wrapping the entire expression in brackets.
Closes #23

Format mathematica: enclose expressions in brackets

---

sources/optimize.cc

As written in https://github.com/vermaseren/form/issues/7#issuecomment-1677266031, this reverts a part of 1d4b775, and somehow fixes the optimization regression.
Actually, I understand neither why it fixes the regression nor what was the intention of [the change](https://github.com/vermaseren/form/commit/1d4b775308c457c9a8ca72aa64890ac9642ec4dd?w=1#diff-b041575ff5a324d5d3b06ee7e9d3ac313fab602aad39112ca26348a28ce039baL4330-R4359).

Fix the FORM5 optimization regression

---

check/examples.frm

This makes the `Test` workflow pass.
To run the disabled tests, use the `-f` (`--full`) option of `check.rb`. Example:
```bash
./check/check.rb build/sources/form -s -f 'Diagrams_*'
```

Temporarily disable Diagrams_1-4 tests that are known to fail

---

check/fixes.frm
sources/poly.cc
sources/polywrap.cc

There are some known issues regarding polyratfun which are not easy to fix.
The least we can do is to crash when we hit something that is definitely wrong, for now.
This "fixes" the example in Issue #336 
This does not catch Issue #270 !

Fix polyratfun bugs caused by incorrect clean flag

---

check/fixes.frm
sources/ftypes.h
sources/function.c
sources/symmetr.c
sources/wildcard.c

Try to fix #268.
I'm still not sure why `EATTENSOR` is called so (maybe there was a certain reason [21 years ago](https://github.com/vermaseren/form/commit/b80588f41583a8ebd6e108f7d9a440f1ecfcd969)).

Remove the hard limit due to EATTENSOR

---

sources/declare.h
sources/ftypes.h
sources/parallel.c
sources/sort.c
sources/threads.c

This allows other code to be included in the lock, in particular to avoid race conditions when temporarity setting `AC.LogHandle = -1` when AM.LogType is 1.
Fixes #470

Move the LogType check inside WriteStats

---

sources/store.c

This addresses #192 and #334 .
Terminating on this condition will certainly break people's existing FORM scripts.
At least print a warning, since one can certainly produce bugs by using names over MAXENAME (16) characters.
An example bug:
```
#-
Off statistics;
Global abcdefghijklmnop = 16;
Global abcdefghijklmnopq = 17;
Global abcdefghijklmnopqr = 18;
Global abcdefghijklmnopqrs = 19;
Global abcdefghijklmnopqrst = 20;
Global abcdefghijklmnopqrstu = 21;
Print +s;
.store
*Save test.res, abcdefghijklmnop, abcdefghijklmnopq;
Save test.res;
.end
```
then
```
#-
Off Statistics;
Load test.res;
Local Abcdefghijklmnop      = abcdefghijklmnop;
Local Abcdefghijklmnopq     = abcdefghijklmnopq;
Local Abcdefghijklmnopqr    = abcdefghijklmnopqr;
Local Abcdefghijklmnopqrs   = abcdefghijklmnopqrs;
Local …
```

Print a warning when saving expr with too-long names

---

check/check.rb

This may be good for writing test cases that give errors/warnings.
Example:
```form
*--#[ example :
Table t(1:3);
Fill t(1) = 1;
Fill t(1) = 2;
.end
assert warning?("Table element was already defined")
*--#] example :
```

test(check.rb): add optional expected_message for error/warning checks

---

check/check.rb

`MesPrint` may insert newline characters for long lines. To verify error/warning messages, we should ignore such newline characters in the output.

test(check.rb): handle continuation lines in verifying error/warning

---

check/fixes.frm
sources/argument.c

We need to call NumberFree each loop iteration, not only upon leaving execarg.
This fixes #508 but I think it needs more testing.

Fix memory leak in makeinteger

---

check/fixes.frm
sources/transform.c

Since the transform statements are sorting into the workspace, and might have to merge patches, make them use a par=1 EndSort. This commit makes this change for all transform statements, though only mularg is going to produce an explosion of terms here.
This fixes #230 and causes #183 to crash with a useful error (Term too complex during normalization).

Change EndSort type for transform statements

---

check/fixes.frm
sources/sort.c
sources/threads.c

These two commits definitely need some more eyes. In particular, there are two more `PutToMaster` calls in `EndSort` that I did not touch yet, probably they need the `sLevel` check as well.
Please check the commit messages for details.

Fix Issue 468

---

sources/threads.c

CompareTerms needs to be able to change flags in the caller's sort struct (PolyWise, for eg). Using the BHEAD macro here does not pass the right struct.
This leads to polyratfun merging bugs when using tform -w2 (which disables the sortbots).
I think changing the argument of MergeWithFloat won't do anything, but just in case some functionality is added there in the future...

Pass the master struct in MasterMerge

---

check/fixes.frm
sources/setfile.c
sources/sort.c

Various buffers in AllocSort depend on the IOsize parameter. At the
main level this is >= MaxTermSize, but this was not the case when
sorting function args, dollar variables.
Fixes the examples in #80 #292

Make sure SIOsize is >= MaxTermSize

---

check/fixes.frm

The test did not create both num,den orderings, as the commentary claimed.
Make cleaner on 32bit systems.

Fix test for Issue 336

---

check/fixes.frm
sources/store.c

It was not intended in #500 that this warning crashes form, which happened here when Save was called in a pre-processor loop. This is due to the leading & of the message which triggers the source file line information. Warning protects from the crash by temporarily setting the "iswarning" variable which causes MesPrint to then not terminate.
This can be easily cleaned up later if Warning is refactored to take a format string and variable arguments.
An alternative would be to move the `static int iswarning;` of `message.c` into one of the header files, but that seems equally as messy as this fix.

Fix termination when saving long-named expressions in a pre-proc loop

---

check/fixes.frm
sources/argument.c

If the argument (or a resulting factor) has more than SubTermsInSmall terms, a par=1 EndSort is necessary to avoid a crash here.
Fixes #563

Use par=1 EndSorts in ArgFactorize

---

check/fixes.frm
sources/poly.cc

These created numerators of 0. Fixes #567

Check for bad terms in fast notation in get_variables

---

check/fixes.frm
sources/optimize.cc

Here are two changes to make the optimizer easier to use.
The first is to dynamically allocate memory in `Horner_tree`, if the `WorkSpace` does not have enough space. There is no particular reason that the workspace should be used for the sort, here, other than that it exists, and might have capacity.
The second, is to re-use the same `WorkPointer` for every call of `Generator` when the optimized expression is placed into FORM's output. `Generator` modifies `AT.WorkPointer` internally, so each term which was added here was placed further and further into the buffer, unnecessarily.
In principle, if you arrive in `generate_expression` with a very-nearly full WorkSpace there could still be a crash. But this should be rare (?) .
These changes pass `pySecDec`'s test suite.

Fix WorkSpace issues with expression optimization

---

check/fixes.frm
sources/execute.c
sources/parallel.c

This fixes #525 by moving the broadcast of the redefined preprocessor variables to after processing each expression, rather than at the end of the module.

ParFORM: fix #525

---

check/features.frm
doc/manual/prepro.tex
doc/manual/setup.tex
doc/manual/statements.tex
sources/compcomm.c
sources/declare.h
sources/execute.c
sources/pre.c
sources/structs.h
sources/threads.c

This is a test of a request from @msloechner , which makes FORM's resident set size better track its actual memory usage. This comes on top of the split allocations branch, since it only deals with the largest buffer. Since FORM allocates its buffers and keeps them for the whole run, the apparent memory usage remains constant after a "peak". If the OS is under memory pressure it will swap pages, but they might be pages that FORM actually isn't using any more.
It seems there are two ways to do it: free and re-allocate the buffer, or use `madvise` to specify `MADV_DONTNEED`. Both have the same effect and have about the same performance, but there is an impact of more than 10% compared to doing nothing. This shouldn't be done by default, and maybe never "every module". (However, the longer …

Optionally reallocate large+small buffer after each module

---

check/features.frm
sources/startup.c

If a bad path for FORMTMPSORT is specified, FORM doesn't notice until it tries to create a sort file and can't. In principle one can create a script which takes a long time to reach this point.
Try to create the file immediately at startup, and Terminate if this fails.

Try to create the sort file at startup.

---

check/fixes.frm
sources/sort.c

Previously, FORM warns only about SmallExtension, even if it is a sub-buffer sort.
This prompts the user to adjust the wrong buffer in the setup.
Fixes #512

Better errors when (Sub)SmallExtension is filled.

---

sources/declare.h
sources/setfile.c
sources/sort.c
sources/threads.c

Add a function argument to AllocSort to specify which buffers are being allocated. This makes it straightforward to print an appropriate warning message.

Better warnings for resized sub-buffers in DEBUGGING mode

---

sources/setfile.c
sources/store.c

Uncommenting this line fixes crashes when loading certain save files, where the sizes of the terms have some interaction with SizeStoreCache.
Changing that value or setting NumStoreCaches to 0 is a works-around also.
Closes #420 and #484

Fix rare FindrNumber/TermRenumber crashes when loading saves

---

.github/workflows/deploy.yml

See: https://github.com/actions/runner-images/issues/10721
Usually, there is a grace period for deprecations, but this time it seems that GitHub gets things done quickly.

Upgrade macOS 12 to 13 in CI

---

check/fixes.frm
sources/wildcard.c

Fix sign error for wildcard powers of dotproducts involving negative vectors

---

INSTALL
check/.rubocop.yml
check/README.md
check/check.rb
check/fixes.frm
configure.ac

This PR depends on the first commit in #511, which improves the portability of the test suite script.
It resolves #580 by updating the Ruby minimum version to 2.0.0. It also improves `--stat` option (order of) output, word size detection for v5.0.0, and includes code refactoring.
Hopefully, later I would like to add some resolution for #581 (warning detection) and update the usage in the README file of the test suite (`check/README.md`), but this PR could be merged as-is.

Enhance test suite

---

sources/threads.c

Add a small sleep in LoadReadjusted to allow threads to aquire the lock. This enormously speeds up some simple tform tests under valgrind.
See also https://github.com/vermaseren/form/issues/600
This effectively just adds "a bit more waiting" to the already-existing `/* Wait a bit.... */` comment.

Alleviate lock contention in the load balancing mechanism

---

.github/workflows/deploy.yml
.github/workflows/test.yml
sources/checkpoint.c
sources/compcomm.c
sources/declare.h
sources/startup.c
sources/structs.h

This is an implementation of deprecation messages like those in  https://github.com/vermaseren/form/issues/475#issuecomment-2146949223 but **at runtime startup** rather than at build time, for Windows, 32bit builds and ParFORM.
End users may not build binaries themselves. 32-bit binaries and ParFORM are distributed by various [distributors](https://repology.org/project/form/versions). We can distribute native Windows binaries if https://github.com/vermaseren/form/pull/511 is merged and `Delete Windows binaries` in `deploy.yml` is removed. This patch will cause these end users to see annoying deprecation warnings.
The deprecation warning looks like, for example, for ParFORM:
```
DeprecationWarning: We are considering deprecating the MPI version (ParFORM).
If you would like support to …
```

Run-time deprecation warning for native Windows, 32-bit systems, ParFORM and Checkpoint

---

.github/workflows/deploy.yml
.github/workflows/test.yml
check/examples.frm
configure.ac
sources/parallel.c

[Ubuntu 20.04 runners are gone](https://github.com/actions/runner-images/issues/11101).
This PR upgrades Ubuntu from 20.04 to 24.04, the latest LTS release.
See also: https://github.com/vermaseren/form/discussions/611
Note that `parvorm` is removed from `valgrind-check` and coverage.
Related: https://github.com/vermaseren/form/issues/429, https://github.com/vermaseren/form/issues/625.

Migrate CI Linux image to Ubuntu 24.04

---

.github/workflows/test.yml
check/check.rb

This patch restricts code coverage to tests checked with Valgrind by using the new `--fake-valgrind` option.
See also discussion in #524.

Restrict code coverage to tests checked with Valgrind

---

check/features.frm
doc/manual/prepro.tex

Add documentation for UNCHANGED_ and ZERO_

---

configure.ac
sources/comexpr.c
sources/declare.h
sources/dict.c
sources/form3.h
sources/minos.c
sources/optimize.cc
sources/parallel.h
sources/polygcd.cc
sources/pre.c
sources/proces.c
sources/reken.c
sources/sch.c
sources/setfile.c
sources/token.c
sources/tools.c

I'm trying to clean up the compilation warnings. Remaining on my system, is a `uninitialized` and a `keyword-macro` (with clang 14).

[WIP] Warnings

---

.github/workflows/deploy.yml
.github/workflows/test.yml
.gitmodules
configure.ac
doc/manual/statements.tex
sources/Makefile.am
sources/compcomm.c
sources/form3.h
sources/minos.c
sources/startup.c

Zstd compression for sort files

---

sources/poly.cc
sources/poly.h
sources/polywrap.cc

`poly::get_variables()` does not need a temporary copy of the input vector containing pointers to function arguments. Passing it by reference rather than by value avoids a heap allocation and a memory copy.

micro-optimization: input vector for poly::get_variables()

---

sources/polywrap.cc
sources/proces.c
sources/sort.c
sources/tools.c

Print the required MaxTermSize in words to allow easy configuration of setup.

Better error "Sorted function argument too long"

---

.github/workflows/deploy.yml
.github/workflows/test.yml
sources/reken.c
sources/structs.h

This closes https://github.com/vermaseren/form/issues/619.

Build arm64-linux binaries in CI

---

.github/workflows/deploy.yml
configure.ac
sources/flintinterface.h

The binaries are now built with the `--with-flint` configure option and statically linked with FLINT.

Include FLINT in release binaries

---

check/fixes.frm
sources/normal.c

Store a pointer to the argument which trails the selected one. The pointer to the selected argument can not be advanced, as it is written over if the terms are different sizes (which accidentally worked previously).
Fixes #642
It is a bit surprising, that this one was only discovered recently.

fix: putfirst_ for un-equally sized args

---

.github/workflows/test.yml

Avoid burning CPU time and clogging up the runners if the normal checks fail.
Also separate parform from check: it takes a long time

ci: make valgrind and coverage require successful check to start

---

sources/sort.c

Revert one change of 1900651, which broke things in case a par=2 EndSort ends up in a file or PObuffer

fix: regression in par=2 EndSort

---

.github/workflows/deploy.yml

Now that windows-2019 is unsupported, move to windows-2022.

ci: bump Windows runner version to windows-2022

---

check/features.frm
sources/declare.h
sources/float.c
sources/fsizes.h
sources/pre.c

This fixes the float printing issue
```
#StartFloat 50
Local F = 1/3;
ToFloat;
Print;
.end
```
that resulted in 
```
F =
3.3e-01;
```
The correct result is now
```
F =
3.333333333333333e-01;
```
Furthermore set the default MZV weight `MAXWEIGHT` to 0 instead of 40.

Fix float printing

---

doc/manual/statements.tex
sources/compcomm.c
sources/sort.c
sources/startup.c
sources/structs.h

feature: add "On humanstats;" for human-readable units in stats

---

check/features.frm
sources/threads.c

The CI often fails due to the timeout test, and needs to be re-run, when it usually will pass. There are two issues:
- Sometimes FORM will terminate after 1s, but not print an error
- In TFORM, particularly under valgrind, SIGALRM is delivered to the wrong thread. Resolve this by specifically blocking SIGALRM on thread creation.
This resolves #612

fix: timeout in tform

---

.github/workflows/test.yml

Timeouts fetching `color.h` from `nikhef.nl` are causing problems every time the formlib cache needs to be updated.
- Fetch form packages from a mirror: https://github.com/form-dev/form-packages
- Add a `-v1` tag to the cache key, which can be incremented when new files are added, so we don't need to remove the existing cache through the github UI.

ci: fetch color.h from the form-packages mirror

---

check/features.frm

FORM can terminate on timeout without printing an error message, with exit status != 0, so assert succeeded? || runtime_error? is not sufficient to catch this. Just don't assert anything. Hitting the test suite timeout still results in a failed test.

test: further fix the timeout test to avoid false failures

---

check/fixes.frm
sources/sort.c

If a par=2 EndSort ends in the PObuffer, don't allocate and copy out of it twice.

fix: memory leak in par=2 EndSort

---

check/examples.frm
check/fixes.frm
doc/manual/polynomials.tex
doc/manual/statements.tex
sources/execute.c

Before this commit FORM only warns when disabling parallel execution in a module if `on allwarnings` is set. This makes sense, since for most of the causes it is not straightforward to modify the code in a way that re-enables parallel execution. However, modifying a dollar variable without a corresponding `moduleoption` statement is often a trivial bug and the user should be warned by default.

Warn by default if parallel execution is vetoed due to dollar variables

---

check/features.frm
check/fixes.frm
sources/evaluate.c
sources/float.c

In this PR, I added tests for the evaluation of every float function. In particular, I tried to catch special values for each function. The tests are checked with Mathematica (and Polylogtools for `mzv_` and `euler_`). 
Furthermore, I aimed to maximize code coverage for `Evaluate.c`. 
A few remarks worth mentioning:
- In the test for `atanh_`, the last digit in `atanh_(.54321)` should actually be a `0`. So, some incorrect rounding happens. Is this related to the rounding in `mpfr`?
- In the test for `euler_`: for `euler_(-1,1,-1)` there is an incorrect rounding at 74 bits of precision.
- I fixed a small bug to evaluate functions if they have `pi_` times a fraction or float as an argument. Do we also want to evaluate if `pi_^2` and `ee_` and `em_` are arguments. This also relates to #687. …

Tests and bug fixes for evaluate

---

sources/sort.c

For scripts which are dominated by level-0 sorting, counting the compares (and not even printing the result) leads to a large performance impact.
Disabled the counting by default.
The per-thread counter still leads to a performance impact, though it is smaller.
---------
This counter was introduced in f1b83ae, which adds the partial binary search to SplitMerge. There a 1.5% performance improvement is claimed for mincer. Possibly this was determined with a single-threaded test?
This change (default: no counter) compared to current master:
| Test | master (s) | Speedup |
|------|--------------|---------|
|trace|5.09|4.51x|
|mincer|70.57|1.28x|
|mass-fact|59.38|1.12x
|forcer|122.23|1.02x|
|mbox1l|2.73|1.00x|
`forcer` and `mbox1l` tests spend a lot of time sorting polyratfun, so they have …

perf: tform: remove default-enabled compare count

---

.github/actions/setup-build/action.yml
.github/workflows/deploy.yml
.github/workflows/test.yml

This patch extracts the build setup logic into a composite action called `setup-build` to avoid repeating similar steps in different jobs. The setup process includes installing dependencies and libraries, extracting tarballs, running `autoreconf`, and executing `configure`.
In the future, if we need to elaborate further on setting up libraries (including building and caching), such as MPI or FLINT, we can manage them all in one place.
There are several ways to organize shared logic in GitHub Actions:
- Script files: Hard to track in the GitHub Actions UI because everything appears as a single step when running a script file.
- [Reusable workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows): Can't set environment variables for the caller. (`setup-build` needs …

ci(refactor): extract build setup logic into setup-build

---

configure.ac
sources/declare.h
sources/flintinterface.cc
sources/flintinterface.h
sources/flintwrap.cc
sources/setfile.c
sources/startup.c

This PR adds checks both at configuration and at runtime to require FLINT 3.2.0 or later. Resolves #679.
~Note: Many test jobs are currently failing due to old FLINT versions.~
**Update**: This PR depends on:
-  #622

Checking FLINT version

---

INSTALL
configure.ac

To maximise compatibility when running on clusters of machines with different CPU feature sets, don't compile with march=native by default.
This anyway doesn't appear to improve performance and possibly even causes perfomance loss: https://github.com/form-dev/form/discussions/705

build: disable native by default
